categories:
- travel
- lifestyle
- tips

page_blocks: []
_array_structures:
  sections:
    values:
      - label: blog text
        icon: text
        value:
          _section-type: blog-text
          text-html:
      - label: blog arches
        icon: image
        value:
          _section-type: blog-arches
          right_image:
          left_image:
      - label: blog fixed
        icon: image
        value:
          _section-type: blog-fixed
          blog-fixed_image:
      - label: window image
        icon: image
        value:
          _section-type: blog-window
          window_image:
      - label: featured text
        icon: text
        value:
          _section-type: blog-text-featured
          featured-text-html:
